In [1]:
!pip install bing-image-downloader

In [2]:
!ls

sample_data


In [3]:
cd/content/drive/My Drive/MLDS

/content/drive/My Drive/MLDS


In [5]:
!ls

In [6]:
!mkdir images

In [7]:
cd images

/content/drive/My Drive/MLDS/images


In [8]:
from bing_image_downloader import downloader
downloader.download("mobile phone",limit=20,output_dir="images")



[!!]Indexing page: 1

[%] Indexed 20 Images on Page 1.


[%] Downloading Image #1 from https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Mobile_phone_evolution.jpg/1200px-Mobile_phone_evolution.jpg
[%] File Downloaded !

[%] Downloading Image #2 from http://2.bp.blogspot.com/-CBlSk3D4hjQ/Uxnb4qcCBQI/AAAAAAAAQOM/Zm9gC_RR1G4/s1600/latest%2Bmobile%2Bphones%2B(1).png
[%] File Downloaded !

[%] Downloading Image #3 from https://ae01.alicdn.com/kf/HTB1HZJidtHO8KJjSZFHq6zWJFXaG/Waterproof-cell-phone-RugGear-RG710-GRANDTOUR-Unlocked-5-0inch-Android-smart-phone-4-core-NFC-Dual.jpg
[%] File Downloaded !

[%] Downloading Image #4 from https://ae01.alicdn.com/kf/HTB1PTQvNFXXXXXlapXXq6xXFXXXR/Original-Waterproof-phone-Mobile-Power-Bank-GSM-Senior-old-man-IP67-Rugged-shockproof-cell-phone-UHF.jpg
[%] File Downloaded !

[%] Downloading Image #5 from http://i.ytimg.com/vi/L6hjWu30AFU/maxresdefault.jpg
[%] File Downloaded !

[%] Downloading Image #6 from https://images.techhive.com/images/art

In [9]:
from bing_image_downloader import downloader
downloader.download("laptop",limit=20,output_dir="images")





[!!]Indexing page: 1

[%] Indexed 20 Images on Page 1.


[%] Downloading Image #1 from https://i.ytimg.com/vi/tIof7h6Pzjs/maxresdefault.jpg
[%] File Downloaded !

[%] Downloading Image #2 from https://i.ytimg.com/vi/B8VfDfyx3oM/maxresdefault.jpg
[%] File Downloaded !

[%] Downloading Image #3 from http://images.tweaktown.com/content/6/5/6539_75_lenovo_thinkpad_w540_mobile_workstation_laptop_review_full.jpg
[%] File Downloaded !

[%] Downloading Image #4 from https://i.ytimg.com/vi/yBx140GQPnc/maxresdefault.jpg
[%] File Downloaded !

[%] Downloading Image #5 from https://i.ytimg.com/vi/DdwcGKnaUew/maxresdefault.jpg
[%] File Downloaded !

[%] Downloading Image #6 from https://icdn3.digitaltrends.com/image/toshiba-p20w-cst3no1-laptop-mainfull1-1200x630-c-ar1.91.jpg?ver=1
[%] File Downloaded !

[%] Downloading Image #7 from https://i.ytimg.com/vi/8FqKBmwfgTs/maxresdefault.jpg
[%] File Downloaded !

[%] Downloading Image #8 from https://i.ytimg.com/vi/7QTnMS8Rh6g/maxresdefault.jpg
[%] Fil

In [12]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import glob
from PIL import Image
import cv2
import os


for i in glob.glob("/content/drive/My Drive/MLDS/images/images/mobile phone/*jpg"):
  b=cv2.imread(i)
  print(b.shape)

(1800, 1200, 3)
(1000, 1000, 3)
(1004, 900, 3)
(720, 1280, 3)
(1682, 2532, 3)
(1000, 1000, 3)
(1582, 1214, 3)
(1000, 1000, 3)
(3083, 1920, 3)
(1131, 1600, 3)
(1000, 1000, 3)
(768, 1024, 3)
(720, 1280, 3)
(1667, 755, 3)
(800, 800, 3)
(3872, 2592, 3)
(720, 1280, 3)
(2000, 2000, 3)
(1800, 1200, 3)


In [14]:
from skimage.io import imread
from skimage.transform import resize
import numpy as np


target = []  
flat_data = []   
images= []

path='/content/drive/My Drive/MLDS/images/images/'
for dirpath, dirnames, filenames in os.walk(path):
  for filename in filenames:
    category = dirpath.split('/')[-1]
    target.append(category)
    img = imread(f'{path}{category}/{filename}')
    img_resized = resize(img,(50,50,3))  
    flat_data.append(img_resized.flatten())
    images.append(img_resized)

flat_data = np.array(flat_data)
target = np.array(target)
images = np.array(images)

print(flat_data.shape)
print(target.shape)
print(images.shape)

(40, 7500)
(40,)
(40, 50, 50, 3)


In [15]:
target

array(['mobile phone', 'mobile phone', 'mobile phone', 'mobile phone',
       'mobile phone', 'mobile phone', 'mobile phone', 'mobile phone',
       'mobile phone', 'mobile phone', 'mobile phone', 'mobile phone',
       'mobile phone', 'mobile phone', 'mobile phone', 'mobile phone',
       'mobile phone', 'mobile phone', 'mobile phone', 'mobile phone',
       'laptop', 'laptop', 'laptop', 'laptop', 'laptop', 'laptop',
       'laptop', 'laptop', 'laptop', 'laptop', 'laptop', 'laptop',
       'laptop', 'laptop', 'laptop', 'laptop', 'laptop', 'laptop',
       'laptop', 'laptop'], dtype='<U12')

In [16]:
import pandas as pd
df=pd.DataFrame(flat_data)
df.head()

0         1         2     ...      7497      7498      7499
0  0.992157  0.986275  0.988235  ...  0.963725  0.951961  0.961765
1  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
2  0.996078  0.996078  0.996078  ...  1.000000  1.000000  1.000000
3  1.000000  1.000000  1.000000  ...  1.000000  1.000000  1.000000
4  0.949020  0.937255  0.941176  ...  0.996078  0.996078  0.996078

[5 rows x 7500 columns]

In [17]:
df['target']=target
df.head()

0         1         2  ...      7498      7499        target
0  0.992157  0.986275  0.988235  ...  0.951961  0.961765  mobile phone
1  0.000000  0.000000  0.000000  ...  0.000000  0.000000  mobile phone
2  0.996078  0.996078  0.996078  ...  1.000000  1.000000  mobile phone
3  1.000000  1.000000  1.000000  ...  1.000000  1.000000  mobile phone
4  0.949020  0.937255  0.941176  ...  0.996078  0.996078  mobile phone

[5 rows x 7501 columns]

In [18]:
x=df.drop(columns=['target'])
y=df['target']

In [19]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=0)
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((30, 7500), (10, 7500), (30,), (10,))

In [20]:
y_test

22          laptop
20          laptop
25          laptop
4     mobile phone
10    mobile phone
15    mobile phone
28          laptop
11    mobile phone
18    mobile phone
29          laptop
Name: target, dtype: object

In [21]:
from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier(n_neighbors=6)
model.fit(x_train,y_train)
pred=model.predict(x_test)
pred

array(['laptop', 'laptop', 'laptop', 'laptop', 'laptop', 'mobile phone',
       'laptop', 'mobile phone', 'mobile phone', 'mobile phone'],
      dtype=object)

In [22]:
import numpy as np
a=np.array(y_test)
a

array(['laptop', 'laptop', 'laptop', 'mobile phone', 'mobile phone',
       'mobile phone', 'laptop', 'mobile phone', 'mobile phone', 'laptop'],
      dtype=object)

In [23]:
y_test

22          laptop
20          laptop
25          laptop
4     mobile phone
10    mobile phone
15    mobile phone
28          laptop
11    mobile phone
18    mobile phone
29          laptop
Name: target, dtype: object

In [24]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,pred))
print(confusion_matrix(y_test,pred))

              precision    recall  f1-score   support

      laptop       0.67      0.80      0.73         5
mobile phone       0.75      0.60      0.67         5

    accuracy                           0.70        10
   macro avg       0.71      0.70      0.70        10
weighted avg       0.71      0.70      0.70        10

[[4 1]
 [2 3]]


In [25]:
z = np.arange(1,25)
z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [26]:
from sklearn.model_selection import GridSearchCV
param={'n_neighbors':z}   
model = KNeighborsClassifier()
model_grid = GridSearchCV(model,param)   
model_grid.fit(x_train,y_train)

GridSearchCV(cv=None, error_score=nan,
             estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                            metric='minkowski',
                                            metric_params=None, n_jobs=None,
                                            n_neighbors=5, p=2,
                                            weights='uniform'),
             iid='deprecated', n_jobs=None,
             param_grid={'n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [27]:
model_grid.best_params_

{'n_neighbors': 11}

In [28]:
from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier(n_neighbors=8)
model.fit(x_train,y_train)
pred=model.predict(x_test)
pred

array(['laptop', 'laptop', 'laptop', 'laptop', 'mobile phone', 'laptop',
       'laptop', 'mobile phone', 'mobile phone', 'mobile phone'],
      dtype=object)

In [29]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,pred))
print(confusion_matrix(y_test,pred))

              precision    recall  f1-score   support

      laptop       0.67      0.80      0.73         5
mobile phone       0.75      0.60      0.67         5

    accuracy                           0.70        10
   macro avg       0.71      0.70      0.70        10
weighted avg       0.71      0.70      0.70        10

[[4 1]
 [2 3]]


In [30]:
from sklearn.linear_model import LogisticRegression as LR
m=LR(class_weight='balanced')
m.fit(x_train,y_train)
pred=m.predict(x_test)
pred

array(['mobile phone', 'laptop', 'laptop', 'mobile phone', 'mobile phone',
       'mobile phone', 'laptop', 'mobile phone', 'mobile phone',
       'mobile phone'], dtype=object)

In [31]:
a

array(['laptop', 'laptop', 'laptop', 'mobile phone', 'mobile phone',
       'mobile phone', 'laptop', 'mobile phone', 'mobile phone', 'laptop'],
      dtype=object)

In [32]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,pred))
print(confusion_matrix(y_test,pred))

              precision    recall  f1-score   support

      laptop       1.00      0.60      0.75         5
mobile phone       0.71      1.00      0.83         5

    accuracy                           0.80        10
   macro avg       0.86      0.80      0.79        10
weighted avg       0.86      0.80      0.79        10

[[3 2]
 [0 5]]


In [33]:
from sklearn.tree import DecisionTreeClassifier as DTC
mod=DTC(class_weight='balanced')
mod.fit(x_train,y_train)
pred=mod.predict(x_test)
pred

array(['laptop', 'laptop', 'mobile phone', 'laptop', 'mobile phone',
       'laptop', 'laptop', 'mobile phone', 'laptop', 'mobile phone'],
      dtype=object)

In [34]:
a

array(['laptop', 'laptop', 'laptop', 'mobile phone', 'mobile phone',
       'mobile phone', 'laptop', 'mobile phone', 'mobile phone', 'laptop'],
      dtype=object)

In [35]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,pred))
print(confusion_matrix(y_test,pred))

              precision    recall  f1-score   support

      laptop       0.50      0.60      0.55         5
mobile phone       0.50      0.40      0.44         5

    accuracy                           0.50        10
   macro avg       0.50      0.50      0.49        10
weighted avg       0.50      0.50      0.49        10

[[3 2]
 [3 2]]


In [36]:
from sklearn import svm
mod=svm.SVC()
mod.fit(x_train,y_train)
pred=mod.predict(x_test)

pred

array(['laptop', 'laptop', 'laptop', 'mobile phone', 'mobile phone',
       'mobile phone', 'laptop', 'mobile phone', 'mobile phone',
       'mobile phone'], dtype=object)

In [37]:
a

array(['laptop', 'laptop', 'laptop', 'mobile phone', 'mobile phone',
       'mobile phone', 'laptop', 'mobile phone', 'mobile phone', 'laptop'],
      dtype=object)

In [38]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,pred))
print(confusion_matrix(y_test,pred))

              precision    recall  f1-score   support

      laptop       1.00      0.80      0.89         5
mobile phone       0.83      1.00      0.91         5

    accuracy                           0.90        10
   macro avg       0.92      0.90      0.90        10
weighted avg       0.92      0.90      0.90        10

[[4 1]
 [0 5]]


In [39]:
from sklearn.ensemble import RandomForestClassifier as RFC
m=RFC()
m.fit(x_train,y_train)
pred=m.predict(x_test)
pred_prob=m.predict_proba(x_test)
print(pred)
print(pred_prob)

['mobile phone' 'laptop' 'laptop' 'laptop' 'mobile phone' 'mobile phone'
 'laptop' 'mobile phone' 'mobile phone' 'mobile phone']
[[0.47 0.53]
 [0.59 0.41]
 [0.59 0.41]
 [0.52 0.48]
 [0.36 0.64]
 [0.4  0.6 ]
 [0.69 0.31]
 [0.18 0.82]
 [0.18 0.82]
 [0.38 0.62]]


In [40]:
a

array(['laptop', 'laptop', 'laptop', 'mobile phone', 'mobile phone',
       'mobile phone', 'laptop', 'mobile phone', 'mobile phone', 'laptop'],
      dtype=object)

In [41]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,pred))
print(confusion_matrix(y_test,pred))

              precision    recall  f1-score   support

      laptop       0.75      0.60      0.67         5
mobile phone       0.67      0.80      0.73         5

    accuracy                           0.70        10
   macro avg       0.71      0.70      0.70        10
weighted avg       0.71      0.70      0.70        10

[[3 2]
 [1 4]]
